"""
MedSpatial AI — Report Service
Generates professional PDF and DOCX reports with scan metadata, reconstruction
summary, AI findings, XAI explanations, and embedded visualizations.
Works on CPU-only environments with no external dependencies.
"""

import base64
import io
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

import numpy as np
from loguru import logger
from PIL import Image


class ReportService:
    """Generates downloadable medical analysis reports in PDF and DOCX formats."""

    DISCLAIMER = (
        "DISCLAIMER: This report was generated by C2Three AI, an artificial intelligence "
        "system. All findings are computer-assisted observations and should NOT be used as a "
        "sole basis for clinical diagnosis. Results must be reviewed and validated by a qualified "
        "radiologist or healthcare professional. This system is intended for research and "
        "educational purposes. Patient data has been processed locally and was not transmitted "
        "to any external service."
    )

    def generate_pdf(
        self,
        scan_metadata: dict[str, Any],
        reconstruction_summary: Optional[dict[str, Any]],
        findings: list[dict[str, Any]],
        tissue_results: Optional[list[dict[str, Any]]],
        reasoning_chains: Optional[list[dict[str, Any]]],
        volume: Optional[np.ndarray],
        output_path: str,
    ) -> str:
        """
        Generate a comprehensive PDF report.

        Returns:
            path to the generated PDF file
        """
        try:
            from reportlab.lib import colors
            from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
            from reportlab.lib.units import inch, mm
            from reportlab.platypus import (
                Image as RLImage,
                Paragraph,
                SimpleDocTemplate,
                Spacer,
                Table,
                TableStyle,
            )
        except ImportError:
            logger.error("reportlab not installed, cannot generate PDF")
            raise ImportError("reportlab is required for PDF generation. pip install reportlab")

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=25 * mm,
            bottomMargin=25 * mm,
        )
        styles = getSampleStyleSheet()
        elements: list = []

        # Custom styles
        title_style = ParagraphStyle(
            "ReportTitle", parent=styles["Title"],
            fontSize=22, spaceAfter=6, textColor=colors.HexColor("#1e3a5f"),
        )
        heading_style = ParagraphStyle(
            "SectionHeading", parent=styles["Heading2"],
            fontSize=14, spaceBefore=16, spaceAfter=8,
            textColor=colors.HexColor("#2563eb"),
        )
        body_style = ParagraphStyle(
            "ReportBody", parent=styles["Normal"],
            fontSize=10, leading=14, alignment=TA_JUSTIFY,
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer", parent=styles["Normal"],
            fontSize=8, leading=10, textColor=colors.gray, alignment=TA_JUSTIFY,
        )

        # ── Header ───────────────────────────────────────────────
        elements.append(Paragraph("MedSpatial AI — Medical Analysis Report", title_style))
        elements.append(Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            ParagraphStyle("Date", parent=body_style, textColor=colors.gray),
        ))
        elements.append(Spacer(1, 12))

        # ── Scan Information ─────────────────────────────────────
        elements.append(Paragraph("1. Scan Information", heading_style))
        scan_data = [
            ["Field", "Value"],
            ["Modality", scan_metadata.get("modality", "Unknown")],
            ["Body Region", scan_metadata.get("body_region", scan_metadata.get("body_part", "Unknown"))],
            ["Study Description", scan_metadata.get("study_description", "N/A")],
            ["Number of Slices", str(scan_metadata.get("num_slices", 0))],
            ["Pixel Spacing", f"{scan_metadata.get('pixel_spacing_x', 'N/A')} × {scan_metadata.get('pixel_spacing_y', 'N/A')} mm"],
            ["Slice Thickness", f"{scan_metadata.get('slice_thickness', 'N/A')} mm"],
        ]
        scan_table = Table(scan_data, colWidths=[150, 300])
        scan_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(scan_table)
        elements.append(Spacer(1, 12))

        # ── Reconstruction Summary ───────────────────────────────
        if reconstruction_summary:
            elements.append(Paragraph("2. Reconstruction Summary", heading_style))
            tissue_data = [["Tissue Layer", "Volume (cm³)", "Vertices", "Mean HU"]]
            tissues = reconstruction_summary.get("tissues", [])
            for t in tissues:
                tissue_data.append([
                    t.get("name", "Unknown"),
                    f"{t.get('volume_mm3', 0) / 1000:.1f}",
                    str(t.get("vertex_count", 0)),
                    f"{t.get('mean_hu', 0):.0f}",
                ])
            if len(tissue_data) > 1:
                tissue_table = Table(tissue_data, colWidths=[130, 100, 100, 100])
                tissue_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#059669")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdf4")]),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]))
                elements.append(tissue_table)
            elements.append(Spacer(1, 12))

        # ── Slice Visualizations ─────────────────────────────────
        if volume is not None:
            elements.append(Paragraph("3. Representative Slices", heading_style))
            slice_images = self._render_slices_to_images(volume)
            for axis_name, img_bytes in slice_images.items():
                try:
                    img = RLImage(io.BytesIO(img_bytes), width=180, height=180)
                    elements.append(Paragraph(f"<b>{axis_name}</b>", body_style))
                    elements.append(img)
                    elements.append(Spacer(1, 6))
                except Exception:
                    pass
            elements.append(Spacer(1, 12))

        # ── AI Findings ──────────────────────────────────────────
        section_num = 4 if volume is not None else 3
        elements.append(Paragraph(f"{section_num}. AI Findings", heading_style))

        if not findings:
            elements.append(Paragraph(
                "No significant anomalies detected. The scan appears within normal limits.",
                body_style,
            ))
        else:
            for i, finding in enumerate(findings, 1):
                severity = finding.get("severity", "unknown")
                severity_color = {
                    "normal": "#10b981", "mild": "#f59e0b",
                    "moderate": "#f97316", "severe": "#ef4444", "critical": "#dc2626",
                }.get(severity, "#6b7280")

                elements.append(Paragraph(
                    f"<b>Finding {i}:</b> "
                    f"<font color='{severity_color}'>[{severity.upper()}]</font> "
                    f"— {finding.get('region', 'Unknown region')}",
                    body_style,
                ))
                elements.append(Paragraph(
                    f"Confidence: {finding.get('confidence', 0):.0%} — "
                    f"{finding.get('description', 'No description')}",
                    body_style,
                ))
                elements.append(Spacer(1, 6))

        elements.append(Spacer(1, 12))

        # ── XAI Reasoning ────────────────────────────────────────
        if reasoning_chains:
            section_num += 1
            elements.append(Paragraph(f"{section_num}. AI Reasoning Chains", heading_style))
            for chain in reasoning_chains:
                elements.append(Paragraph(
                    f"<b>{chain.get('finding', 'Finding')}</b> "
                    f"(Confidence: {chain.get('confidence', 0):.0%})",
                    body_style,
                ))
                for step in chain.get("steps", []):
                    elements.append(Paragraph(
                        f"  • [{step.get('category', '')}] {step.get('description', '')}",
                        body_style,
                    ))
                differential = chain.get("differential", [])
                if differential:
                    elements.append(Paragraph(
                        f"  Differential: {', '.join(differential)}", body_style,
                    ))
                elements.append(Spacer(1, 8))

        # ── AI Model Transparency ────────────────────────────────
        section_num += 1
        elements.append(Paragraph(f"{section_num}. AI Model Information", heading_style))
        elements.append(Paragraph(
            "Models used: SpatialTransformer3D (feature extraction), "
            "AnomalyGraph/GAAT (PatchCore-3D + GraphSAGE, disease classification), "
            "SegmentationNet3D (3D U-Net, tissue segmentation), "
            "LayerDissector (HU thresholding + neural refinement).",
            body_style,
        ))
        elements.append(Paragraph(
            "All AI models ship with random/pretrained weights. Production-grade "
            "results require training on validated medical datasets.",
            body_style,
        ))
        elements.append(Spacer(1, 16))

        # ── Disclaimer ───────────────────────────────────────────
        elements.append(Paragraph(self.DISCLAIMER, disclaimer_style))

        # Build PDF
        doc.build(elements)
        logger.info(f"PDF report generated: {output_path}")
        return output_path

    def generate_docx(
        self,
        scan_metadata: dict[str, Any],
        reconstruction_summary: Optional[dict[str, Any]],
        findings: list[dict[str, Any]],
        tissue_results: Optional[list[dict[str, Any]]],
        reasoning_chains: Optional[list[dict[str, Any]]],
        volume: Optional[np.ndarray],
        output_path: str,
    ) -> str:
        """Generate a comprehensive DOCX report."""
        try:
            from docx import Document
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.shared import Inches, Pt, RGBColor
        except ImportError:
            logger.error("python-docx not installed")
            raise ImportError("python-docx is required for DOCX generation. pip install python-docx")

        doc = Document()

        # Title
        title = doc.add_heading("MedSpatial AI — Medical Analysis Report", level=0)
        title.runs[0].font.color.rgb = RGBColor(0x1E, 0x3A, 0x5F)
        doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        # Scan information
        doc.add_heading("1. Scan Information", level=1)
        table = doc.add_table(rows=1, cols=2)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Field"
        hdr[1].text = "Value"
        info_items = [
            ("Modality", scan_metadata.get("modality", "Unknown")),
            ("Body Region", scan_metadata.get("body_region", scan_metadata.get("body_part", "Unknown"))),
            ("Study Description", scan_metadata.get("study_description", "N/A")),
            ("Slices", str(scan_metadata.get("num_slices", 0))),
            ("Pixel Spacing", f"{scan_metadata.get('pixel_spacing_x', 'N/A')} x {scan_metadata.get('pixel_spacing_y', 'N/A')} mm"),
            ("Slice Thickness", f"{scan_metadata.get('slice_thickness', 'N/A')} mm"),
        ]
        for field, value in info_items:
            row = table.add_row().cells
            row[0].text = field
            row[1].text = str(value)

        # Reconstruction summary
        if reconstruction_summary:
            doc.add_heading("2. Reconstruction Summary", level=1)
            t_table = doc.add_table(rows=1, cols=4)
            t_table.style = "Light Grid Accent 1"
            hdr = t_table.rows[0].cells
            hdr[0].text = "Tissue"
            hdr[1].text = "Volume (cm³)"
            hdr[2].text = "Vertices"
            hdr[3].text = "Mean HU"
            for t in reconstruction_summary.get("tissues", []):
                row = t_table.add_row().cells
                row[0].text = t.get("name", "")
                row[1].text = f"{t.get('volume_mm3', 0) / 1000:.1f}"
                row[2].text = str(t.get("vertex_count", 0))
                row[3].text = f"{t.get('mean_hu', 0):.0f}"

        # Slice images
        if volume is not None:
            doc.add_heading("3. Representative Slices", level=1)
            slice_images = self._render_slices_to_images(volume)
            for axis_name, img_bytes in slice_images.items():
                doc.add_paragraph(axis_name)
                doc.add_picture(io.BytesIO(img_bytes), width=Inches(2.5))

        # Findings
        section_num = 4 if volume is not None else 3
        doc.add_heading(f"{section_num}. AI Findings", level=1)
        if not findings:
            doc.add_paragraph("No significant anomalies detected.")
        else:
            for i, finding in enumerate(findings, 1):
                p = doc.add_paragraph()
                run = p.add_run(f"Finding {i}: [{finding.get('severity', 'unknown').upper()}] ")
                severity = finding.get("severity", "unknown")
                severity_colors = {
                    "normal": RGBColor(0x10, 0xB9, 0x81),
                    "mild": RGBColor(0xF5, 0x9E, 0x0B),
                    "moderate": RGBColor(0xF9, 0x73, 0x16),
                    "severe": RGBColor(0xEF, 0x44, 0x44),
                }
                run.font.color.rgb = severity_colors.get(severity, RGBColor(0x6B, 0x72, 0x80))
                run.font.bold = True
                p.add_run(f"— {finding.get('region', '')}")
                doc.add_paragraph(
                    f"Confidence: {finding.get('confidence', 0):.0%} — "
                    f"{finding.get('description', '')}"
                )

        # XAI
        if reasoning_chains:
            section_num += 1
            doc.add_heading(f"{section_num}. AI Reasoning", level=1)
            for chain in reasoning_chains:
                doc.add_paragraph(
                    f"{chain.get('finding', '')} (Confidence: {chain.get('confidence', 0):.0%})",
                    style="List Bullet",
                )
                for step in chain.get("steps", []):
                    doc.add_paragraph(
                        f"[{step.get('category', '')}] {step.get('description', '')}",
                        style="List Bullet 2",
                    )

        # Disclaimer
        section_num += 1
        doc.add_heading(f"{section_num}. Disclaimer", level=1)
        disclaimer_p = doc.add_paragraph()
        run = disclaimer_p.add_run(self.DISCLAIMER)
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)

        doc.save(output_path)
        logger.info(f"DOCX report generated: {output_path}")
        return output_path

    def _render_slices_to_images(
        self, volume: np.ndarray
    ) -> dict[str, bytes]:
        """Render middle slices in 3 planes as PNG byte arrays."""
        images: dict[str, bytes] = {}

        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
        except ImportError:
            logger.warning("matplotlib not available, skipping slice images")
            return images

        planes = {
            "Axial (Middle)": volume[volume.shape[0] // 2, :, :],
            "Coronal (Middle)": volume[:, volume.shape[1] // 2, :],
            "Sagittal (Middle)": volume[:, :, volume.shape[2] // 2],
        }

        for plane_name, slice_2d in planes.items():
            try:
                fig, ax = plt.subplots(1, 1, figsize=(2, 2), dpi=75)  # Reduced size and DPI
                # Window for mediastinum view
                windowed = np.clip(slice_2d, -200, 400)
                windowed = (windowed - windowed.min()) / (windowed.max() - windowed.min() + 1e-8)
                ax.imshow(windowed, cmap="gray", aspect="auto")
                ax.set_title(plane_name, fontsize=8)
                ax.axis("off")
                plt.tight_layout()

                buf = io.BytesIO()
                fig.savefig(buf, format="png", bbox_inches="tight", facecolor="white", dpi=75)  # Reduced DPI
                plt.close(fig)
                buf.seek(0)
                images[plane_name] = buf.read()
            except Exception as exc:
                logger.warning(f"Failed to render {plane_name}: {exc}")

        return images
